# Netlify configuration for React + Vite frontend
[build]
  command = "npm run build"
  publish = "front/dist"

# Si quieres definir variables de entorno:
#[build.environment]
#  VITE_API_URL = "https://ofialumnos.vercel.app/api"

[[redirects]]
  from = "/api/*"
  to = "http://localhost:3001/:splat"
  status = 200
  force = true
