# Netlify configuration for React + Vite frontend
[build]
  command = "npm run build"
  publish = "front/dist"

env = { 
  # Variables de entorno para el frontend (si usas VITE_*)
  # VITE_API_URL = "https://tu-backend-production.com" 
}

[[redirects]]
  from = "/api/*"
  to = "http://localhost:3001/:splat"
  status = 200
  force = true
